name: Deploy React Demo to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Add required permissions
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type check
        run: bun run typecheck

      - name: Lint
        run: bun run lint

      - name: Run tests
        run: bun test

      - name: Build library
        run: bun run build

      - name: Build demo
        run: |
          cd demo
          echo "Installing demo dependencies..."
          bun install
          echo "Building demo..."
          bun run build
          echo "Build complete! Checking output..."
          if [ -d "dist" ]; then
            echo "✅ dist folder exists"
            ls -la dist/
            if [ -f "dist/index.html" ]; then
              echo "✅ index.html exists"
              echo "First few lines of index.html:"
              head -5 dist/index.html
            else
              echo "❌ index.html missing!"
              exit 1
            fi
          else
            echo "❌ dist folder missing!"
            exit 1
          fi
          cd ..

      - name: Upload Pages artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: demo/dist

      - name: Debug what we're uploading
        if: github.ref == 'refs/heads/main'
        run: |
          echo "=== DEBUGGING UPLOAD ==="
          echo "Contents of demo/dist that will be deployed:"
          find demo/dist -type f -name "*.html" -o -name "*.js" -o -name "*.css" | head -10
          echo ""
          echo "index.html content (first 20 lines):"
          head -20 demo/dist/index.html || echo "No index.html found!"
          echo ""
          echo "All files in demo/dist:"
          ls -la demo/dist/

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
